#!/bin/bash

echo "=== PRUEBA FASE 2.3 - RESERVA REAL CON GOOGLE CALENDAR ==="
echo ""
echo "1. Verificar que el servidor esté corriendo:"
curl -s http://localhost:10000/health | jq . || echo "Error: ¿Servidor corriendo en puerto 10000?"
echo ""
echo "2. Probar endpoint de chat (debería funcionar):"
curl -s -X POST http://localhost:10000/api/chat \
  -H "Content-Type: application/json" \
  -d '{"sessionId":"test-123","message":"hola"}' | jq '.reply | length' && echo "✓ Chat funciona"
echo ""
echo "3. Probar endpoint de disponibilidad:"
curl -s "http://localhost:10000/api/availability?block=1" | jq '.dates[0]' && echo "✓ Disponibilidad funciona"
echo ""
echo "4. IMPORTANTE: Prueba manual necesaria:"
echo "   a. Abrir navegador en http://localhost:10000"
echo "   b. Seleccionar fecha y hora en el calendario"
echo "   c. Completar formulario con datos reales"
echo "   d. Hacer clic en 'Reservar Videollamada'"
echo "   e. Verificar que aparece 'Procesando reserva...'"
echo "   f. Verificar que aparece modal con link de Google Meet real"
echo "   g. Verificar que el evento aparece en Google Calendar del abogado"
echo "   h. Verificar que se envía email de confirmación"
echo ""
echo "5. Variables de entorno necesarias para Google Calendar:"
echo "   - CLIENT_ID, CLIENT_SECRET, REFRESH_TOKEN"
echo "   - LAWYER_EMAIL"
echo "   - CALENDAR_TIMEZONE (opcional, default: America/Santiago)"
echo ""
echo "=== FIN DE PRUEBAS FASE 2.3 ==="
